name: Environment secrets

on:
  workflow_dispatch:
#  pull_request:
#    branches: [main]
#  push:
#    branches: [main]
#  issue_comment:
#    types: [created]

jobs:
  call-shared-from-comment:
    uses: ./.github/workflows/shared.yml
    if: github.event.issue.pull_request != '' && github.event.comment.body != ''
    secrets: inherit
    with:
      the-env: ${{github.event.comment.body}}
      
  call-shared-from-other:
    uses: ./.github/workflows/shared.yml
    if: github.event.comment.body == ''
    secrets: inherit
    with:
      the-env: qa
