name: Deploy

on:
  issue_comment:
    types: [created]
  workflow_call:
        
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.event.issue }}
      - run: echo ${{ github.event }}
      - run: echo ${{ github }}
