name: Shared

on:
  workflow_call:
    inputs:
      the-env:
        description: The environment to run the end-to-end tests against
        required: true
        type: string
    
jobs:
  echo:
    permissions:
      checks: write
    name: Echo secret
    runs-on: ubuntu-latest
    environment: ${{inputs.the-env}}
    steps:
      - run: 'echo "Per env: ${{secrets.PER_ENV}}"'
