name: Shared

on:
  workflow_call:
    inputs:
      the-env:
        description: The environment to run the end-to-end tests against
        required: true
        type: string

permissions:
  checks: write

jobs:
  echo:
    name: Echo secret
    runs-on: ubuntu-latest
    environment: ${{inputs.the-env}}
    steps:
      - run: 'echo "Per env: ${{secrets.PER_ENV}}"'
      - name: Leave finished notification
        uses: actions/github-script@v6
        env:
          ENV: ${{ inputs.the-env }}
        with:
          script: |
            // Add a commit status to the current commit
            await github.rest.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              'success',
              target_url,
              description: `Well down on running ${process.env.ENV}.`,
              context: process.env.STATUS_CONTEXT,
            });
